#custom_dir: mkdocs_alabaster
site_name: Test docs
site_description: 'A docs test'
site_author: 'Michael Hausenblas'
docs_dir: docs/
repo_name: 'mhausenblas/mkdocs-template'
repo_url: 'https://github.com/mhausenblas/mkdocs-template'

# Configuration
theme:
  name: 'material'

# Page tree
nav:
  - Introduction: index.md
#   - License: license.md
#   - General Installation: installation.md
#   - geeadd tools:
#     - Quota tool: projects/quota.md
#     - GEE app source: projects/app2script.md
#     - Search GEE data catalog: projects/search.md
#   - Asset management tools:
#     - Copy Assets: projects/copy.md
#     - Move Assets: projects/move.md
#     - Change asset permissions: projects/access.md
#     - Delete assets: projects/delete.md
#   - Additional tools:
#     - Asset Size: projects/size.md
#     - Asset Report: projects/report.md
#     - Task status: projects/task_status.md
#     - Cancel tasks: projects/cancel_tasks.md
#     - Delete asset metadata: projects/delete_metadata.md
#   - Changelog: changelog.md
